#!/bin/bash
# Lab 1.8 : Synthèse - Analyse d'une requête HTTP complète
# Objectif : Consolider toutes les connaissances des couches réseau

set -e

echo "=== Lab 1.8 : Analyse complète d'une requête HTTP ==="
echo ""

echo "🎯 Objectif : Suivre une requête HTTP de bout en bout"
echo "   et identifier chaque couche OSI impliquée"
echo ""

# Vider tous les caches
echo "1. Vidage des caches..."
echo "   - Cache ARP..."
sudo ip neigh flush all
echo "   - Cache DNS..."
sudo systemd-resolve --flush-caches 2>/dev/null || sudo resolvectl flush-caches 2>/dev/null || true
echo "✓ Caches vidés"
echo ""

echo "2. ⚠️  INSTRUCTIONS WIRESHARK :"
echo "   - Ouvrez Wireshark"
echo "   - Appliquez le filtre : arp || dns || tcp.port == 80"
echo "   - Cliquez sur 'Start capturing'"
echo ""
read -p "Appuyez sur Entrée quand Wireshark est prêt..."
echo ""

# Effectuer une requête HTTP
echo "3. Exécution de la requête HTTP vers example.com..."
echo ""
curl -v http://example.com
echo ""

echo "=========================================="
echo "📊 GUIDE D'ANALYSE DANS WIRESHARK"
echo "=========================================="
echo ""
echo "Vous devriez observer les étapes suivantes dans l'ordre chronologique :"
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  Étape │ Protocole │ Couche │ Description                      ║"
echo "╠════════════════════════════════════════════════════════════════╣"
echo "║  1     │ DNS       │ 7      │ Requête: 'Quelle est l'IP ?'     ║"
echo "║  2     │ DNS       │ 7      │ Réponse: 'IP = 93.184.216.34'    ║"
echo "║  3     │ ARP       │ 2      │ Requête: 'MAC de passerelle ?'   ║"
echo "║  4     │ ARP       │ 2      │ Réponse: 'MAC = AA:BB:CC:...'    ║"
echo "║  5     │ TCP SYN   │ 4      │ Initiation connexion port 80     ║"
echo "║  6     │ TCP SYN-ACK│ 4     │ Acceptation par serveur          ║"
echo "║  7     │ TCP ACK   │ 4      │ Confirmation, connexion OK       ║"
echo "║  8     │ HTTP GET  │ 7      │ Requête de la page               ║"
echo "║  9     │ HTTP 200  │ 7      │ Réponse avec contenu             ║"
echo "║  10    │ TCP FIN   │ 4      │ Fermeture de connexion           ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Pour chaque paquet, notez :"
echo ""
echo "📦 Couche 2 (Ethernet) :"
echo "   - Adresse MAC source"
echo "   - Adresse MAC destination"
echo "   - Type de protocole (EtherType)"
echo ""
echo "📦 Couche 3 (IP) :"
echo "   - Adresse IP source"
echo "   - Adresse IP destination"
echo "   - TTL"
echo ""
echo "📦 Couche 4 (TCP/UDP) :"
echo "   - Port source"
echo "   - Port destination"
echo "   - Flags TCP (SYN, ACK, FIN, etc.)"
echo "   - Numéros de séquence et accusé de réception"
echo ""
echo "📦 Couche 7 (Application) :"
echo "   - Méthode HTTP (GET, POST, etc.)"
echo "   - Code de statut (200, 404, etc.)"
echo "   - Headers HTTP"
echo "   - Contenu de la réponse"
echo ""
echo "=========================================="
echo "🎓 QUESTIONS DE RÉFLEXION"
echo "=========================================="
echo ""
echo "1. Pourquoi la requête ARP va-t-elle vers la passerelle et non vers example.com ?"
echo ""
echo "2. Combien de paquets TCP sont nécessaires pour établir la connexion ?"
echo ""
echo "3. Les adresses MAC changent-elles quand le paquet traverse un routeur ?"
echo ""
echo "4. Les adresses IP changent-elles (hors NAT) ?"
echo ""
echo "5. Pourquoi la résolution DNS se fait-elle en premier ?"
echo ""
echo "6. Que se passerait-il si le cache DNS avait déjà l'IP d'example.com ?"
echo ""
echo "=========================================="
echo "✅ Analyse terminée"
echo "=========================================="
